# -*- coding: utf-8 -*-
"""fibonacciRecursivo.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13YGksQVtTOtUd9dcbwwV1PEEJUIUTh9S
"""

class FibonacciRecursivo:
    def __init__(self, n):
        """
        Inicializa la clase con el índice del número de Fibonacci que se desea calcular.

        :param n: Índice en la sucesión (debe ser entero no negativo)
        """
        self.n = n

    def calcular(self):
        """
        Método público que devuelve el n-ésimo número de Fibonacci.

        :return: Número de Fibonacci en la posición n
        """
        return self._fibonacci_recursivo(self.n)

    def _fibonacci_recursivo(self, n):
        """
        Método recursivo privado para calcular el número de Fibonacci.

        :param n: Índice actual en la recursión
        :return: Número de Fibonacci correspondiente
        """
        if n == 0 or n == 1:
            return n
        else:
            return self._fibonacci_recursivo(n - 1) + self._fibonacci_recursivo(n - 2)


# Ejemplo de uso:
fib = FibonacciRecursivo(6)
print(fib.calcular())  # Salida esperada: 8